import type { TemplateType } from '@/lib/models/collection/template'

// HTML exacto de la tabla de facturas — no modificar
const INVOICE_TABLE_HTML = `<table class="tiptap-table" style="width: 100%; table-layout: fixed; border-collapse: collapse; margin-top: 10px; font-size: 14px;"><colgroup></colgroup><tbody><tr style="background-color: rgb(243, 244, 246);"><th style="width: 20%; padding: 8px; border: 1px solid rgb(229, 231, 235); text-align: center; font-size: 14px;"><p>No. Factura</p></th><th style="width: 20%; padding: 8px; border: 1px solid rgb(229, 231, 235); text-align: center;"><p>Monto</p></th><th style="width: 20%; padding: 8px; border: 1px solid rgb(229, 231, 235); text-align: center;"><p>Fecha</p></th><th style="width: 20%; padding: 8px; border: 1px solid rgb(229, 231, 235); text-align: center;"><p>Vencimiento</p></th><th style="width: 20%; padding: 8px; border: 1px solid rgb(229, 231, 235); text-align: center;"><p>Días</p></th></tr><tr><td colspan="0" rowspan="1" style="padding: 8px; border: 1px solid rgb(229, 231, 235); font-family: monospace; font-size: 10px; color: rgb(107, 114, 128);"><p>{{#each invoices}}</p></td><td colspan="0" rowspan="1"><p></p></td><td colspan="0" rowspan="1"><p></p></td><td colspan="0" rowspan="1"><p></p></td><td colspan="0" rowspan="1"><p></p></td><td colspan="1" rowspan="1"><p></p></td><td colspan="1" rowspan="1"><p></p></td><td colspan="1" rowspan="1"><p></p></td><td colspan="1" rowspan="1"><p></p></td><td colspan="1" rowspan="1"><p></p></td></tr><tr><td colspan="0" rowspan="1" style="padding: 8px; border: 1px solid rgb(229, 231, 235); font-size: 14px;"><p>{{invoice_number}}</p></td><td colspan="0" rowspan="1" style="padding: 8px; border: 1px solid rgb(229, 231, 235); text-align: left; font-size: 14px;"><p>{{amount_due}}</p></td><td colspan="0" rowspan="1" style="padding: 8px; border: 1px solid rgb(229, 231, 235); text-align: left; font-size: 14px;"><p>{{invoice_date}}</p></td><td colspan="0" rowspan="1" style="padding: 8px; border: 1px solid rgb(229, 231, 235); text-align: left; font-size: 14px;"><p>{{due_date}}</p></td><td colspan="0" rowspan="1" style="padding: 8px; border: 1px solid rgb(229, 231, 235); text-align: left; font-size: 14px;"><p>{{days_overdue}}</p></td><td colspan="1" rowspan="1"><p></p></td><td colspan="1" rowspan="1"><p></p></td><td colspan="1" rowspan="1"><p></p></td><td colspan="1" rowspan="1"><p></p></td><td colspan="1" rowspan="1"><p></p></td></tr><tr><td colspan="0" rowspan="1" style="padding: 8px; border: 1px solid rgb(229, 231, 235); font-family: monospace; font-size: 10px; color: rgb(107, 114, 128);"><p>{{/each}}</p></td><td colspan="0" rowspan="1"><p></p></td><td colspan="0" rowspan="1"><p></p></td><td colspan="0" rowspan="1"><p></p></td><td colspan="0" rowspan="1"><p></p></td><td colspan="1" rowspan="1"><p></p></td><td colspan="1" rowspan="1"><p></p></td><td colspan="1" rowspan="1"><p></p></td><td colspan="1" rowspan="1"><p></p></td><td colspan="1" rowspan="1"><p></p></td></tr></tbody></table>`

const AVISO_LEGAL_HTML = `<p><span style="font-size: 12px; color: black;"><strong>Aviso Legal</strong></span></p><blockquote><p style="text-align: justify;"><span style="font-size: 11px; color: black;">Este correo lo tenemos registrado en nuestra base de datos como contacto corporativo (dato público). Si no desea continuar recibiendo comunicaciones de nuestra empresa, le agradecemos informarnos al respecto. El contenido de este mensaje y sus archivos adjuntos es de carácter confidencial y de uso exclusivo para el destinatario. Si lo recibió por error, por favor elimínelo y notifique al remitente, absteniéndose de reproducir o divulgar su contenido.</span></p></blockquote>`

export interface QuickTemplate {
  id: string
  name: string
  description: string
  subject: string
  template_type: TemplateType
  badge: string
  badgeColor: 'green' | 'amber' | 'red'
  content_html: string
}

export const QUICK_TEMPLATES: QuickTemplate[] = [
  {
    id: 'quick-pronto-pago',
    name: 'Notificación Pronto Pago',
    description:
      'Recordatorio amigable para clientes con pagos próximos a vencer. Ideal para mantener la relación comercial y anticipar el cobro.',
    subject: 'Notificación Pronto Pago',
    template_type: 'email',
    badge: 'Recordatorio',
    badgeColor: 'green',
    content_html: `<p><span style="font-size: 14px; color: rgb(0, 0, 0);">Estimado cliente,</span></p><p></p><p><span style="font-size: 14px; color: rgb(0, 0, 0);">Esperamos que se encuentre muy bien. Nos permitimos hacerle un cordial recordatorio sobre las siguientes obligaciones que próximamente vencen con nuestra compañía, con el fin de que pueda programar su pago de manera oportuna y continuar disfrutando de nuestros servicios sin ninguna interrupción.</span></p><p></p><p><span style="font-size: 14px;"><strong>NIT</strong>: {{nit}}</span></p><p><span style="font-size: 14px;"><strong>EMPRESA</strong>: {{company_name}}</span></p><p></p><p><span style="font-size: 14px;"><strong>Total de Facturas</strong>: {{total_invoices}}</span></p><p></p>${INVOICE_TABLE_HTML}<p></p><p style="text-align: left;"><span style="font-size: 14px;">Valoramos enormemente su confianza y la relación comercial que hemos construido juntos. Si ya realizó el pago correspondiente, agradecemos hacer caso omiso de este mensaje o informarnos para actualizar nuestros registros.</span></p><p style="text-align: left;"></p><p style="text-align: left;"><span style="font-size: 14px; color: rgb(36, 36, 36);">Quedamos a su disposición para cualquier inquietud sobre la facturación.</span></p><p style="text-align: left;"></p><p style="text-align: left;"><span style="font-size: 10pt; color: rgb(0, 0, 0);"><strong>Cordialmente,</strong></span></p><p style="text-align: left;"></p><p style="text-align: left;"><span style="font-size: 14px; color: rgb(0, 0, 0);"><strong>Departamento de Cartera</strong></span></p><p></p>${AVISO_LEGAL_HTML}<p></p>`,
  },
  {
    id: 'quick-prejuridico',
    name: 'Programación de Cobro',
    description:
      'Comunicación formal para cartera con mora avanzada. Expresa urgencia y abre la puerta a un acuerdo.',
    subject: 'Programación de Pago — Gestión Prejurídica',
    template_type: 'email',
    badge: 'Moderado',
    badgeColor: 'amber',
    content_html: `<p><span style="font-size: 14px; color: rgb(0, 0, 0);">Estimado cliente,</span></p><p></p><p><span style="font-size: 14px; color: rgb(0, 0, 0);">Relacionamos a continuación las obligaciones que a la fecha adeuda con nuestra compañía, las cuales han excedido el plazo convenido para su cancelación llegando a</span><span style="font-size: 14px; color: rgb(36, 36, 36);"> <strong>{{total_days_overdue}}</strong> </span><span style="font-size: 14px;"><strong>días de Mora.</strong></span></p><p></p><p><span style="font-size: 14px;"><strong>NIT</strong>: {{nit}}</span></p><p><span style="font-size: 14px;"><strong>EMPRESA</strong>: {{company_name}}</span></p><p></p><p><span style="font-size: 14px;"><strong>Cartera : {{total_amount_due}}</strong></span></p><p><span style="font-size: 14px;"><strong>Total de Facturas</strong>: {{total_invoices}}</span></p><p></p>${INVOICE_TABLE_HTML}<p></p><p style="text-align: left;"><span style="font-size: 14px;">Para nosotros es muy importante contar con los pagos oportunos de parte de nuestros clientes ya que son recursos importantes para cubrir nuestras obligaciones como compañía.</span></p><p style="text-align: left;"><span style="font-size: 14px; color: rgb(36, 36, 36);">Agradecemos mucho una pronta respuesta de la programación de pago.</span></p><p style="text-align: left;"></p><p style="text-align: left;"><span style="font-size: 10pt; color: rgb(0, 0, 0);"><strong>Cordialmente,</strong></span></p><p style="text-align: left;"></p><p style="text-align: left;"><span style="font-size: 14px; color: rgb(0, 0, 0);"><strong>Departamento de Cartera</strong></span></p><p></p>${AVISO_LEGAL_HTML}<p></p>`,
  },
  {
    id: 'quick-juridico',
    name: 'Programación de Cobro Jurídico',
    description:
      'Notificación formal del inicio de proceso ejecutivo. Tono firme y legal, con apertura para regularización antes del proceso judicial.',
    subject: 'Notificación de Proceso Jurídico — Cartera Vencida',
    template_type: 'email',
    badge: 'Jurídico',
    badgeColor: 'red',
    content_html: `<p><span style="font-size: 14px; color: rgb(0, 0, 0);">Estimado cliente,</span></p><p></p><p><span style="font-size: 14px; color: rgb(0, 0, 0);">Por medio de la presente, le informamos que las obligaciones que a continuación se detallan han superado <strong>{{total_days_overdue}} días de mora</strong>, sin que a la fecha se haya registrado gestión de pago alguna. Ante el incumplimiento reiterado del plazo convenido, nuestra compañía procederá a trasladar el expediente a la Dirección Jurídica para el inicio del correspondiente <strong>proceso ejecutivo de cobro</strong>.</span></p><p></p><p><span style="font-size: 14px; color: rgb(180, 0, 0);">Le advertimos que el inicio de este proceso conlleva costos adicionales por concepto de honorarios de abogados e intereses de mora, los cuales serán asumidos íntegramente por el deudor, de acuerdo con lo estipulado en los términos y condiciones de su contrato.</span></p><p></p><p><span style="font-size: 14px;"><strong>NIT</strong>: {{nit}}</span></p><p><span style="font-size: 14px;"><strong>EMPRESA</strong>: {{company_name}}</span></p><p></p><p><span style="font-size: 14px;"><strong>Cartera Total: {{total_amount_due}}</strong></span></p><p><span style="font-size: 14px;"><strong>Total de Facturas</strong>: {{total_invoices}}</span></p><p></p>${INVOICE_TABLE_HTML}<p></p><p style="text-align: left;"><span style="font-size: 14px;">Si desea evitar el inicio del proceso judicial, le exhortamos a contactarse con nuestro Departamento de Cartera a la mayor brevedad posible para acordar un esquema de pago. Tenga en cuenta que dispone de un plazo máximo de <strong>5 días hábiles</strong> a partir de la recepción de este comunicado para regularizar su situación antes de que el caso sea escalado definitivamente.</span></p><p style="text-align: left;"></p><p style="text-align: left;"><span style="font-size: 14px;">Lamentamos haber llegado a esta instancia y confiamos en que podremos resolver esta situación de forma ágil, preservando la relación comercial que nos ha unido.</span></p><p style="text-align: left;"></p><p style="text-align: left;"><span style="font-size: 10pt; color: rgb(0, 0, 0);"><strong>Cordialmente,</strong></span></p><p style="text-align: left;"></p><p style="text-align: left;"><span style="font-size: 14px; color: rgb(0, 0, 0);"><strong>Dirección Jurídica y Departamento de Cartera</strong></span></p><p></p>${AVISO_LEGAL_HTML}<p></p>`,
  },
]
