export { Frame0ROI } from './Frame0ROI'
export { Frame1Security } from './Frame1Security'
export { Frame2Telemetry } from './Frame2Telemetry'
export { Frame3Integrity } from './Frame3Integrity'
export { Frame4Plataform } from './Frame4Plataform'
export { Frame5Gobernance } from './Frame5Gobernance'
export { Frame6Close } from './Frame6Close'
